import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The sidebar is generated from the docs/ filesystem: each section directory
// has an index.md whose frontmatter (sidebar_position, sidebar_label) controls
// ordering and labels.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
